spring:
  profiles:
    include: oauth
  jpa:
    open-in-view: false
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/dev_wiki?serverTimezone=UTC&characterEncoding=UTF-8
    username: devwiki
    password: devwiki
    driver-class-name: com.mysql.cj.jdbc.Driver