spring:

  jpa:
    open-in-view: false
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/dev_wiki?serverTimezone=UTC&characterEncoding=UTF-8
    username: devwiki
    password: devwiki
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    host: localhost

  session:
    store-type: redis  # 우리가 사용할 세션 저장소는 Redis
    redis:
      namespace: devwiki:session

es:
  host: localhost:9200

cors:
  allow:
    frontend: http://localhost:3001


server:
  servlet:
    session:
      cookie:
        path: / # 도메인에 사용될 수 있는 경로를 나타냄.
        name: JSESSIONID
        http-only: true
        secure: false # https로 통신할때는 true로 변경해야 함.
      timeout: 3600


logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG